#!/usr/bin/env php
<?php

declare(strict_types=1);

require_once __DIR__.'/vendor/autoload.php';

use HeadFirstDesignPatterns\SimUDuck\AbstractDuck;
use HeadFirstDesignPatterns\SimUDuck\Ducks\DecoyDuck;
use HeadFirstDesignPatterns\SimUDuck\Ducks\RubberDuck;
use HeadFirstDesignPatterns\SimUDuck\Ducks\MallardDuck;
use HeadFirstDesignPatterns\SimUDuck\Ducks\RedheadDuck;

/** @var AbstractDuck[] $duckList */
$duckList = [
    new MallardDuck(),
    new RedheadDuck(),
    new RubberDuck(),
    new DecoyDuck(),
];

$countDucks = count($duckList) - 1;

foreach ($duckList as $index => $duck) {
    $duck->display();

    print_r("Duck says:\n");
    $duck->quack();

    print_r("Duck doing:\n");
    $duck->swim();
    $duck->fly();

    if ($index < $countDucks) {
        print_r("\n=============\n\n");
    }
}
